name: Sync Elastic and VCS Dev Rules

on:
  workflow_dispatch:
    inputs:
      space:
        description: 'Specify the Kibana space to export rules from'
        required: false
        default: 'dev'

jobs:
  fetch-dev-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install requests detection-rules

      - name: Export Rules from Elastic Security and Import Rules to TOML
        env:
          DR_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID }}
          DR_KIBANA_USER: ${{ secrets.ELASTIC_USERNAME }}
          DR_KIBANA_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
          CUSTOM_RULES_DIR: custom_rules/dev
        run: |
          # Clear the directory before exporting new rules
          rm -rf ${{ env.CUSTOM_RULES_DIR }}
          mkdir -p ${{ env.CUSTOM_RULES_DIR }}/rules
          
          # Export the rules from Kibana and import them to the custom rules directory
          python -m detection_rules kibana --space "${{ github.event.inputs.space }}" export-rules --directory ${{ env.CUSTOM_RULES_DIR }}/rules/ -e -ac -s -sv

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add custom_rules/dev
          git commit -m "Sync dev rules from Elastic Cloud" || echo "No changes to commit"
          git push
